
package jaxws.rpcstyle;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldInterface", targetNamespace = "http://rpcStyle.JAXWS/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://rpcStyle.JAXWS/HelloWorldInterface/getHelloWorldAsStringRequest", output = "http://rpcStyle.JAXWS/HelloWorldInterface/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns jaxws.rpcstyle.HashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://rpcStyle.JAXWS/HelloWorldInterface/getEmployeMapRequest", output = "http://rpcStyle.JAXWS/HelloWorldInterface/getEmployeMapResponse")
    public HashMap getEmployeMap();

}
