
package jaxws.rpcstyle;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HellowWorldIMPLService", targetNamespace = "http://rpcStyle.JAXWS/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class HellowWorldIMPLService
    extends Service
{

    private final static URL HELLOWWORLDIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWWORLDIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWWORLDIMPLSERVICE_QNAME = new QName("http://rpcStyle.JAXWS/", "HellowWorldIMPLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWWORLDIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWWORLDIMPLSERVICE_EXCEPTION = e;
    }

    public HellowWorldIMPLService() {
        super(__getWsdlLocation(), HELLOWWORLDIMPLSERVICE_QNAME);
    }

    public HellowWorldIMPLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWWORLDIMPLSERVICE_QNAME, features);
    }

    public HellowWorldIMPLService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWWORLDIMPLSERVICE_QNAME);
    }

    public HellowWorldIMPLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWWORLDIMPLSERVICE_QNAME, features);
    }

    public HellowWorldIMPLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HellowWorldIMPLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "HellowWorldIMPLPort")
    public HelloWorldInterface getHellowWorldIMPLPort() {
        return super.getPort(new QName("http://rpcStyle.JAXWS/", "HellowWorldIMPLPort"), HelloWorldInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "HellowWorldIMPLPort")
    public HelloWorldInterface getHellowWorldIMPLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpcStyle.JAXWS/", "HellowWorldIMPLPort"), HelloWorldInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWWORLDIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOWWORLDIMPLSERVICE_EXCEPTION;
        }
        return HELLOWWORLDIMPLSERVICE_WSDL_LOCATION;
    }

}
